server {
    listen 80;

    location /api/ {
        proxy_pass ${BACKEND_URL}/api/;
        client_max_body_size 50M;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}